### ISSUE TITLE
Total fetched doesn't include shipping price

### ISSUE THREAD

**Issue by Mesuva** [edbeeny/community_store_sagepay#3]
This line:
https://github.com/edbeeny/community_store_sagepay/blob/985490b24ea9741dfb651d4890908d974ab1cc3f/src/SagePay/SagePay.php#L33

needs to be
```
query .= '&Amount=' . number_format($order->getTotal(), 2, '.', '');
```
Whilst StoreCalculator::getGrandTotal() normally includes all totals, at this point in the processing I think the order has been placed so the shipping method is reset, so it needs to fetch it directly from the order record.

**Comment by edbeeny** [comment]
Thank you mesuva for the fix :)
